-- Init

/* IMAGE */

CREATE SEQUENCE image_db_id START WITH 1 MINVALUE 1 MAXVALUE 999999999;

CREATE TABLE image (image_db_id INTEGER NOT NULL, name VARCHAR(256), image_path VARCHAR(256), type VARCHAR(10), version INTEGER NOT NULL, creation_date DATE NOT NULL, updating_date DATE);


/* UNIT */
CREATE SEQUENCE unit_db_id START WITH 1 MINVALUE 1 MAXVALUE 999999999;

CREATE TABLE unit ( unit_db_id INTEGER NOT NULL, name VARCHAR(256), abbreviation VARCHAR(5), version INTEGER NOT NULL, creation_date DATE NOT NULL, updating_date DATE);

/* COOK BOOK */
CREATE SEQUENCE cookbook_db_id START WITH 1 MINVALUE 1 MAXVALUE 999999999;

CREATE TABLE cookbook (cookbook_db_id INTEGER NOT NULL, name VARCHAR(256) NOT NULL, image_db_id INTEGER, version INTEGER NOT NULL, creation_date DATE NOT NULL, updating_date DATE);

/* INGREDIENT */
CREATE SEQUENCE ingredient_db_id START WITH 1 MINVALUE 1 MAXVALUE 999999999;

CREATE TABLE ingredient (ingredient_db_id INTEGER NOT NULL, name VARCHAR(256) NOT NULL, image_db_id INTEGER, quantity INTEGER NOT NULL, unit_db_id INTEGER NOT NULL, recipe_db_id INTEGER, version INTEGER NOT NULL, creation_date DATE NOT NULL, updating_date DATE);


/* RECIPE */
CREATE SEQUENCE recipe_db_id START WITH 1 MINVALUE 1 MAXVALUE 999999999;

CREATE TABLE recipe(recipe_db_id INTEGER NOT NULL, cookbook_db_id INTEGER NOT NULL, title VARCHAR(256), preheat CHAR(1), version INTEGER NOT NULL, creation_date DATE NOT NULL, updating_date DATE);


/* RECIPE STEP */
CREATE SEQUENCE recipe_step_db_id START WITH 1 MINVALUE 1 MAXVALUE 999999999;

CREATE TABLE recipe_step(recipe_step_db_id INTEGER NOT NULL, recipe_db_id INTEGER NOT NULL, text VARCHAR(2048), version INTEGER NOT NULL, creation_date DATE NOT NULL, updating_date DATE);


ALTER TABLE image ADD CONSTRAINT PK_IMAGE PRIMARY KEY (image_db_id);
ALTER TABLE unit ADD CONSTRAINT PK_UNIT PRIMARY KEY (unit_db_id);
ALTER TABLE cookbook ADD CONSTRAINT PK_COOKBOOK PRIMARY KEY (cookbook_db_id);
ALTER TABLE ingredient ADD CONSTRAINT PK_INGREDIENT PRIMARY KEY (ingredient_db_id);
ALTER TABLE recipe ADD CONSTRAINT PK_RECIPE PRIMARY KEY (recipe_db_id);
ALTER TABLE recipe_step ADD CONSTRAINT PK_RECIPE_STEP PRIMARY KEY (recipe_step_db_id, recipe_db_id);

ALTER TABLE cookbook ADD CONSTRAINT FK_IMAGE_COOKBOOK FOREIGN KEY (image_db_id) REFERENCES image(image_db_id);
ALTER TABLE ingredient ADD CONSTRAINT FK_IMAGE_INGREDIENT FOREIGN KEY (image_db_id) REFERENCES image(image_db_id);
ALTER TABLE ingredient ADD CONSTRAINT FK_RECIPE_INGREDIENT FOREIGN KEY (recipe_db_id) REFERENCES recipe(recipe_db_id);
ALTER TABLE ingredient ADD CONSTRAINT FK_UNIT_INGREDIENT FOREIGN KEY (unit_db_id) REFERENCES unit(unit_db_id);
ALTER TABLE recipe ADD CONSTRAINT FK_RECIPE_COOKBOOK FOREIGN KEY (cookbook_db_id) REFERENCES cookbook(cookbook_db_id);
ALTER TABLE recipe_step ADD CONSTRAINT FK_RECIPE_RECIPE_STEP FOREIGN KEY (recipe_db_id) REFERENCES recipe(recipe_db_id);

